    <div class="container-fluid">
		<div class="row">
			<div class="col-md-4 col-md-offset-4"><br/>
			  <form class="form-horizontal" role="form" method="post"
				action="<?php echo $this->basePath(); ?>/user/createUser">
				<fieldset>
				  <!-- Form Name -->
				  <legend>Cadastro de Estudantes</legend>

				  <!-- Text input-->
				  <div class="form-group">
					<div class="col-sm-12">
					  <input name="name" type="text" placeholder="Nome Completo" class="form-control">
					</div>
				  </div>

				  <!-- Text input-->
				  <div class="form-group">
					<div class="col-sm-12">
					  <input name = "ra" type="text" placeholder="RA" class="form-control">
					</div>
				  </div>

				  <!-- Text input-->
				  <div class="form-group">
					<div class="col-sm-12">
					  <input name = "email" type="text" placeholder="Email" class="form-control">
					</div>
				  </div>
				  
				  <!-- Text input-->
				  <div class="form-group">
					<div class="col-sm-6">
					  <div class="radio">
						  <label><input type="radio" name="sexo" value = "0">F</label>
						</div>
					</div>

					<div class="col-sm-6">
					  <div class="radio">
						  <label><input type="radio" name="sexo" value = "1">M</label>
						</div>
					</div>
				  </div>

				  <!-- Text input-->
				  <div class="form-group">
					<div class="col-sm-6">
					  <input name = "password" type="password" placeholder="Senha" class="form-control">
					</div>

					<div class="col-sm-6">
					  <input type="password" placeholder="Confirmar Senha" class="form-control">
					</div>
				  </div>

				  <div class="form-group">
					<div class="col-sm-offset-3 col-sm-10">
					  <div class="pull-center">
						<button type="reset" class="btn btn-default">Limpar</button>
						<button type="submit" class="btn btn-primary">Enviar</button>
					  </div>
					</div>
				  </div>

				</fieldset>
			  </form>
			</div><!-- /.col-lg-12 -->
		</div><!-- /.row -->
	</div>