<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Storage\Module'                        => __DIR__ . '/Module.php',
    'Storage\Controller\StorageController' => __DIR__ . '/src/Storage/Controller/StorageController.php',
    'StorageTest\Framework\TestCase'        => __DIR__ . '/tests/Storage/Framework/TestCase.php',
    'StorageTest\SampleTest'                => __DIR__ . '/tests/Storage/SampleTest.php',
);
