<div class="container">
	<div class="row">
		<h4 align="left">Buscar por aluno</h4>
           <div id="custom-search-input">
                            <div align="right" class="input-group col-md 12">
                                <input type="text" class="  search-query form-control" placeholder="Procurar" />
                                <span class="input-group-btn">
                                    <button class="btn btn-danger" type="button">
                                        <span class=" glyphicon glyphicon-search"></span>
                                    </button>
                                </span>
                            </div>
                        </div>
	</div>
	<span><br></span>
	<div>
	<h2 align="center">Relatório</h2>
	</div>
	
		<div class="table-responsive">
		<table class="table table-bordered">
			<thead class="sortable">
				<tr>
					<th>Nome</th>
					<th>Ferramentas</th>
				</tr>
			</thead>
				
		    <tbody>
		    <tr>
				<td> Karen Yasmin de Oliveira Vicente</td>
				<td>
					<a class="glyphicon glyphicon-list-alt" href='#' rel="tooltip" data-container="body" data-placement="bottom" title="Gerar relatório"></a> <span></span><a class="glyphicon glyphicon-envelope" href='#' rel="tooltip" data-container="body" data-placement="bottom" title="Enviar relatório"></a>
					
				</td>
			</tr>
		    </tbody>
		</table>
	</div>
</div>

