<pre>
Caro usuário,

Sua requisição para troca de senha foi concluída com sucesso. <a href="<?php echo $this->token?>">Clicando aqui</a> poderá definir uma nova senha.
O prazo para definir uma nova senha é de três dias, caso ultrapasse, favor solicitar novamente.

Qualquer dúvida por favor contatar o administrador do sistema.

</pre>
<small>Obs.: Este é um e-mail automático, por gentiliza não respondê-lo.</small>

<p>
<span style="font-size:8.0pt;font-family:&quot;Arial&quot;,sans-serif;color:#7f7f7f;background:white">Este e-mail foi emitido pelo Portal do projeto MSA-BNDES (<a href="http://www.funcate.org.br/msa" target="_blank">www.funcate.org.br/msa</a>). Seu conteúdo e eventuais arquivos transmitidos com ele são confidenciais
 e destinam-se exclusivamente para o uso do indivíduo ou entidade a quem estão dirigidos. Se você recebeu esta mensagem por engano, por favor notifique a gerência do departamento de Geoprocessamento da FUNCATE pelo endereço <a href="mailto:gerenciageo@funcate.org.br" target="_blank">gerenciageo@funcate.org.br</a> e apague
 definitivamente este e-mail de seu sistema. Se você não for o destinatário pretendido, a FUNCATE o notifica que divulgar, copiar, distribuir ou tomar qualquer ação relacionada ao conteúdo desta informação é estritamente vedado.<u></u><u></u></span>
</p>