<?php
use Storage\Entity\User;
use Zend\Session\Container;

$session = new Container('App_Auth');
$user = null;
if(get_class($session->user)=='Storage\Entity\User'){
	$user=$session->user;
}
?>
<html lang="pt">
    <head>
        <meta charset="UTF-8">        
        <?php echo $this->headTitle('WebServer Unity')->setSeparator(' - ')->setAutoEscape(false); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        				->prependStylesheet($this->basePath() . '/css/bootstrap-switch.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style-bndes.css')
                        ->prependStylesheet($this->basePath() . '/css/multi-select.css')
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/tablesorter.css');
        ?>
        <!-- Scripts -->
        <?php echo $this->headScript()
        	->prependFile($this->basePath() . '/js/jquery.mask.min.js')
        	->prependFile($this->basePath() . '/js/user-config-validate.js')
        	->prependFile($this->basePath() . '/js/validate-forms.js')
        	->prependFile($this->basePath() . '/js/bootstrap-switch.min.js')
        	->prependFile($this->basePath() . '/js/onload-page-events.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/main.js')
            ->prependFile($this->basePath() . '/js/workspace-window.js')
            ->prependFile($this->basePath() . '/js/jquery.capslockstate.js')
            ->prependFile($this->basePath() . '/js/jquery.tablesorter.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
        	->prependFile($this->basePath() . '/js/analytics.js');
        ?>
    </head>
    <body>
	    <div class="container">
			<div class="row clearfix">
				<div class="col-md-12 column">
					<div class="page-header">
						<h1>
						WebServer Unity
						</h1>
					</div>
				</div>
			</div>
			<div class="row clearfix">
				<div class="col-md-12 column">
					<nav class="navbar navbar-default" role="navigation">
						<div class="navbar-header">
							 <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
							 <span class="sr-only">Alterna nevegação</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button> <a class="navbar-brand" href="<?php echo $this->basePath().'/'; ?>"><span class="glyphicon glyphicon-home "></span></a>							
							<?php 
									if(isset($user)){
									    if($user->role->isTeacher){
								?>
										 <a class="navbar-brand" href="<?php echo $this->basePath().'/report/viewReport'; ?>">Consultar Relatórios</a>
								<?php }
									    }?>
						</div>
						
						<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						<?php 
									if(isset($user)){
									    if($user->role->isAdmin){
								?>
							<ul class="nav navbar-nav">
								<li class="dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown">Cadastros<strong class="caret"></strong></a>
									<ul class="dropdown-menu">
										<li>
											<a href="<?php echo $this->basePath(); ?>/user/listUser">Usuários</a>
            								    </li>
            								    <li>
            								        <a href="<?php echo $this->basePath(); ?>/question/listQuestion">Questões</a>
            								    </li>
            								    <li>
            								        <a href="<?php echo $this->basePath(); ?>/competence/listCompetence">Competências</a>
            								    </li>
            								    <li>
            								        <a href="<?php echo $this->basePath(); ?>/answer/listAnswer">Respostas</a>
            								    </li>
            								    <li>
            								        <a href="<?php echo $this->basePath(); ?>/institution/listInstitution">Instituição</a>
            								    </li>
            								    <li>
            								        <a href="<?php echo $this->basePath(); ?>/teacher/listTeacher">Professores</a>
            								    </li>
            						</ul>
								</li>
							</ul>
							<?php 
									    }
									}
									    
								?>
							<?php
							$html_form='';
							if(!isset($user)) {
								$html_form=''.
								'<form action="'.$this->basePath().'/auth/loginServer" method="post" class="navbar-form navbar-right">'.
									'<div class="form-group">'.
										'<input class="form-control input-sm" type="text" name="email" id="email" placeholder="Email" />'.
									'</div>&nbsp;'.
									'<div class="form-group">'.
										'<input class="form-control input-sm" type="password" name="password" id="password" placeholder="Senha" />'.
									'</div>&nbsp;'.
									'<button type="submit" class="btn btn-default input-sm">Login <span class="glyphicon glyphicon-log-in"></span></button> '.
									'<p class="capsWarning"><span id="statetext"></span></p>'.
								'</form>';
							}else{
                                $function = "location.href='".$this->basePath()."/auth/change'";
								$html_form=''.
								'<form action="'.$this->basePath().'/auth/logoutServer" method="post" class="navbar-form navbar-right">'.
									'<div class="form-group">'.
										'Olá '.$user->name.'&nbsp;'.
									'</div>';
									$html_form = $html_form . '<button type="submit" class="btn btn-default input-sm"> Logout <span class="glyphicon glyphicon-log-out"></span></button>';
								$html_form = $html_form .'</form>';
							}
							echo $html_form;
							?>
						</div>				
					</nav>
				</div>
			</div>
		</div>
		<br />
			<?php
				$flash = $this->flashMessenger();
				$flash->setMessageOpenFormat('<div%s>
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">
				    &times;
				</button>
				<div>')->setMessageCloseString('</div></div>');
				
				echo $flash->render('home-error', array('alert', 'alert-dismissable', 'alert-danger', 'alert-messages', 'flash-messages'));
				echo $flash->render('home-info', array('alert', 'alert-dismissable', 'alert-info', 'alert-messages', 'flash-messages'));
				echo $flash->render('home-warning', array('alert', 'alert-dismissable', 'alert-warning', 'alert-messages', 'flash-messages'));
				echo $flash->render('home-success', array('alert', 'alert-dismissable', 'alert-success', 'alert-messages', 'flash-messages'));
			?>
		<br /><br />
        <?php echo $this->content; ?>
        <br /><br />


		 <?php echo $this->inlineScript(); ?>
    </body>
</html>