    <div class="container-fluid">
		<div class="row">
			<div class="col-md-4 col-md-offset-4"><br/>
			  <form class="form-horizontal" role="form" method="post"
				action="<?php echo $this->basePath(); ?>/competence/createCompetence">
				<fieldset>
				  <!-- Form Name -->
				  <legend>Cadastro de Competência</legend>

				  <!-- Text input-->
				  <div class="form-group">
					<div class="col-sm-12">
					  <input name="description" type="text" placeholder="descrição" class="form-control">
					</div>
				  </div>

				  <div class="form-group">
					<div class="col-sm-offset-3 col-sm-10">
					  <div class="pull-center">
						<button type="reset" class="btn btn-default">Limpar</button>
						<button type="submit" class="btn btn-primary">Enviar</button>
					  </div>
					</div>
				  </div>

				</fieldset>
			  </form>
			</div><!-- /.col-lg-12 -->
		</div><!-- /.row -->
	</div>