<div class="divUsers">
	<h1 class="text-center">Perguntas</h1>
	<br />
	<br />
	<p>
        <a class="btn btn-primary" href="<?php echo $this->basePath(); ?>/competence/createCompetence" rel="tooltip" data-container="body" data-placement="bottom" title="Criar uma competencia"><span class="glyphicon glyphicon-plus"></span> Novo</a>
	</p>
	<div class="table-responsive">
		<table class="table table-bordered">
			<thead class="sortable">
				<tr>
					<th>ID</th>
					<th>descrição</th>
					<th>Ferramentas</th>
				</tr>
			</thead>
				<?php if($this->competencies) { ?>
				
		    <tbody>
		    <?php foreach($this->competencies as $competence): ?>
		    <tr>
				<td ><?php echo $competence->competenceId; ?></td>
				<td ><?php echo $competence->description; ?></td>

				<td>
					<a class="glyphicon glyphicon-edit" href='<?php echo $this->basePath()."/competence/createCompetence?id=".$competence->competenceId; ?>' rel="tooltip" data-container="body" data-placement="bottom" title="Modificar competencia"></a>
				</td>
			</tr>
		    <?php endforeach; }?>
		    </tbody>
		</table>
	</div>
	<br />
	
</div>
<script>
var basePath = '<?php echo $this->basePath(); ?>';
</script>